# Generated by Django 5.1 on 2024-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo do Candidato:')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do Resposavel:')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone para contado:')),
                ('endereco', models.TextField(blank=True, max_length=255, verbose_name='Endereço:')),
                ('irmaos', models.CharField(choices=[('Não', 'Não Tenho'), ('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais')], max_length=20, verbose_name='Tem irmãos?')),
                ('unidade', models.CharField(choices=[('Primavera', 'Unidade Primavera'), ('Bela Vista', 'Unidade Bela Vista')], max_length=50)),
                ('nivel', models.CharField(choices=[('Maternal Babay', 'Maternal Babay'), ('1º ano Fundamental I', '1º ano Fundamental I'), ('2º ano Fundamental I', '2º ano Fundamental I'), ('3º ano Fundamental I', '3º ano Fundamental I'), ('4º ano Fundamental I', '4º ano Fundamental I'), ('5º ano Fundamental II', '5º ano Fundamental II'), ('6º ano Fundamental II', '6º ano Fundamental II'), ('7º ano Fundamental II', '7º ano Fundamental II'), ('8º ano Fundamental II', '8º ano Fundamental II'), ('9º ano Fundamental II', '9º ano Fundamental II'), ('1ª Série do Ensino Médio', '1ª Série do Ensino Médio'), ('2ª Série do Ensino Médio', '2ª Série do Ensino Médio'), ('3ª Série do Ensino Médio', '3ª Série do Ensino Médio')], max_length=50)),
                ('motivo_bolsa', models.TextField(max_length=255)),
            ],
        ),
    ]
