# Generated by Django 5.1 on 2024-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='motivo_bolsa',
            field=models.TextField(),
        ),
    ]
