# Generated by Django 5.1 on 2024-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_remove_inscricao_motivo_bolsa_inscricao_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone para contato:'),
        ),
    ]
