# Generated by Django 5.1 on 2024-08-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_alter_inscricao_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
