# Generated by Django 5.1 on 2024-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_alter_inscricao_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='escola',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Escola que já estudou'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Maternal Babay', 'Maternal Babay'), ('1º ano Fundamental I', '1º ano Fundamental I'), ('2º ano Fundamental I', '2º ano Fundamental I'), ('3º ano Fundamental I', '3º ano Fundamental I'), ('4º ano Fundamental I', '4º ano Fundamental I'), ('5º ano Fundamental II', '5º ano Fundamental II'), ('6º ano Fundamental II', '6º ano Fundamental II'), ('7º ano Fundamental II', '7º ano Fundamental II'), ('8º ano Fundamental II', '8º ano Fundamental II'), ('9º ano Fundamental II', '9º ano Fundamental II'), ('1ª Série do Ensino Médio', '1ª Série do Ensino Médio'), ('2ª Série do Ensino Médio', '2ª Série do Ensino Médio'), ('3ª Série do Ensino Médio', '3ª Série do Ensino Médio')], max_length=50, null=True),
        ),
    ]
