# Generated by Django 5.1 on 2024-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_alter_inscricao_escola_alter_inscricao_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='confirmacao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Eu confirmo que as informações fornecidas estão corretas'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='irmaos',
            field=models.CharField(blank=True, choices=[('Não', 'Não Tenho'), ('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais')], max_length=20, null=True, verbose_name='Tem irmãos?'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='selecao',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Grupos Whatsapp', 'Grupos Whatsapp'), ('Coordenação / Professores', 'Coordenação / Professores'), ('Pais', 'Pais'), ('Alunos', 'Alunos')], default='Não informado', max_length=50, null=True),
        ),
    ]
