# Generated by Django 5.1 on 2024-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_alter_inscricao_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='unidade',
            field=models.CharField(blank=True, choices=[('Primavera', 'Unidade Primavera'), ('Bela Vista', 'Unidade Bela Vista')], max_length=50),
        ),
    ]
